export const GET_MERN_PROJECTS = 'GET_MERN_PROJECTS';
export const GET_REACT_PROJECTS = 'GET_REACT_PROJECTS';
export const GET_JAVASCRIPT_PROJECTS = 'GET_JAVASCRIPT_PROJECTS';
export const GET_CNET_PROJECTS = 'GET_CNET_PROJECTS';
export const GET_PHP_PROJECTS = 'GET_PHP_PROJECTS';
